# Generated by Django 3.2.3 on 2021-07-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalPages', '0005_auto_20210705_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='RoyalSite/static/RoyalSite/images/gallery/x.png`', upload_to='RoyalSite/static/RoyalSite/images/gallery'),
        ),
    ]
