# Generated by Django 3.2.3 on 2021-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalPages', '0009_alter_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='background',
            field=models.ImageField(default='gallery/x.png', upload_to='RoyalSite/static/RoyalSite/images/gallery'),
        ),
    ]
