# Generated by Django 3.2.3 on 2021-06-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='RoyalSite/images/'),
        ),
    ]
