# Generated by Django 3.2.3 on 2021-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalPages', '0006_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='RoyalSite/static/RoyalSite/images/gallery/x.png', upload_to='RoyalSite/static/RoyalSite/images/gallery'),
        ),
    ]
