# Generated by Django 3.2.3 on 2021-07-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoyalPages', '0008_blogpost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
