# Generated by Django 3.2.3 on 2021-10-11 01:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RoyalPages', '0011_alter_aboutus_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='RoyalArcSite/backgrounds'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='media\x08ackgrounds\\defualt_images.png', max_length=255, verbose_name='RoyalArcSite/covers'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='RoyalArcSite/gallery'),
        ),
    ]
